### ISSUE TITLE
Integrate Cluster API Provider Tinkerbell(CAPT) into Sandbox 

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/roadmap#15]
Cluster API Provider Tinkerbell is not properly integrated into the [Sandbox](https://github.com/tinkerbell/sandbox). This would be extremely valuable improving the development cycle of CAPT.

**Comment by chrisdoherty4** [comment]
Issue moved to https://github.com/tinkerbell/sandbox/issues/165
